language: java
jdk:
  - openjdk7

cache:
  directories:
    - '$HOME/.m2/repository'

install: /bin/true
script:
  - mvn clean install -B --settings .mvntravissettings.xml && mvn clean cobertura:cobertura coveralls:report

